### ISSUE TITLE
Error when try to play example scene

### ISSUE THREAD

**Issue by nguyenthanhloc191919** [BitBurst-GmbH/bitlabs-unity-package#1]
Helloo, can you help me fix this bug ?

This error where i just press play button, seem it is initial error

![image](https://github.com/BitBurst-GmbH/bitlabs-unity-package/assets/50568539/34aae1d0-6d33-4d1b-9640-41546c485b5f)

This is error where i click on show survey button

![image](https://github.com/BitBurst-GmbH/bitlabs-unity-package/assets/50568539/e916e872-8a28-4854-a909-765d06e3cc59)

**Comment by omaRaad** [comment]
@nguyenthanhloc191919  The scene is tested on an Android Emulator. I don't think you can run it in the Unity Editor

**Comment by nguyenthanhloc191919** [comment]
Thank you so much for reading my post. Yes, i knew it will work on android device. But when i built apk and test it with android logcat, it show error like below:

![image](https://github.com/BitBurst-GmbH/bitlabs-unity-package/assets/50568539/740ec003-cb05-4c8b-b516-c8386daabf55)

**Comment by omaRaad** [comment]
Please give me all the important data, like the Android version, Gradle version, Unity version, etc.

**Comment by nguyenthanhloc191919** [comment]
- Unity version 2021.3.33
- Gradle version 6.1.1
- Android Gradle Plug-in version 4.0.1

**Comment by nguyenthanhloc191919** [comment]
I think problem is here, init function has problem.

![image](https://github.com/BitBurst-GmbH/bitlabs-unity-package/assets/50568539/1efc3c90-1d10-4d43-bba5-077bf7f92393)

**Comment by omaRaad** [comment]
@nguyenthanhloc191919  Did you resolve Android libraries via the External Dependency Manager?

**Comment by nguyenthanhloc191919** [comment]
i resolved before and it show these errors:

Resolve failed due to com.github.BitBurst-GmbH.bitlabs-android-library:unity:3.1.20+ missing for project :, attempted to use com.github.BitBurst-GmbH.bitlabs-android-library:unity:3.1.20+, failed due to org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find any version that matches com.github.BitBurst-GmbH.bitlabs-android-library:unity:3.1.20+.

**Comment by nguyenthanhloc191919** [comment]
Okay, i also tried to change version at BitLabsDependencies.xml to com.github.BitBurst-GmbH.bitlabs-android-library:unity:3.1.22 and i resolved android libraries successful. But when i built apk and test it again with android logcat, still get same errors like before when click on show survey button.

![image](https://github.com/BitBurst-GmbH/bitlabs-unity-package/assets/50568539/25119c6a-b774-4860-b49a-00658e14bb39)

![image](https://github.com/BitBurst-GmbH/bitlabs-unity-package/assets/50568539/f15d2876-d9a7-43a0-8aa3-8f23c6598854)

**Comment by omaRaad** [comment]
@nguyenthanhloc191919 
You can't change the SDK version that is used for resolution as other versions haven't been tested for this Unity SDK version.

There was an issue in the artifact not being found in the Jitpack Repository. But I fixed it now. 
So please restore the SDK version to **3.1.20** and retry the resolution.

**Comment by nguyenthanhloc191919** [comment]
I don't know why, when i resolve again, i got this error:

![image](https://github.com/BitBurst-GmbH/bitlabs-unity-package/assets/50568539/869dc407-9726-46c0-9926-9178d0e3fc3c)

**Comment by nguyenthanhloc191919** [comment]
Yes, i restored sdk version to 3.1.20 again, then i resolved libraries but still got same errors when testing on android device.

![image](https://github.com/BitBurst-GmbH/bitlabs-unity-package/assets/50568539/2951f4fe-0b52-4b5b-a5bf-c0ec5dff5bc5)

**Comment by nguyenthanhloc191919** [comment]
Helloo,

Have you found error at init method yet ? I restore back to version 3.1.20
and resolve library successful. But when i built apk and tested it with
android logcat, it still showed same error before and when i click on show
survey button, it's not working because init method failed.

Hope you can help me fix this issue at Unity BitLabs SDK. Thank you for
reading my mail.

Best regards.
Loc Nguyen

**Comment by omaRaad** [comment]
Please send the full logs... the BitLabs class should be found after successful resolution.

@nguyenthanhloc191919

**Comment by nguyenthanhloc191919** [comment]
Okay, here it is full log:

2024/02/06 00:08:58.595 4151 4212 Error Unity AndroidJavaException: java.lang.ClassNotFoundException: ai.bitlabs.sdk.BitLabs
2024/02/06 00:08:58.595 4151 4212 Error Unity java.lang.ClassNotFoundException: ai.bitlabs.sdk.BitLabs
2024/02/06 00:08:58.595 4151 4212 Error Unity 	at java.lang.Class.classForName(Native Method)
2024/02/06 00:08:58.595 4151 4212 Error Unity 	at java.lang.Class.forName(Class.java:453)
2024/02/06 00:08:58.595 4151 4212 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2024/02/06 00:08:58.595 4151 4212 Error Unity 	at com.unity3d.player.UnityPlayer.access$500(Unknown Source:1)
2024/02/06 00:08:58.595 4151 4212 Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:115)
2024/02/06 00:08:58.595 4151 4212 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:102)
2024/02/06 00:08:58.595 4151 4212 Error Unity 	at android.os.Looper.loop(Looper.java:193)
2024/02/06 00:08:58.595 4151 4212 Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:21)
2024/02/06 00:08:58.595 4151 4212 Error Unity Caused by: java.lang.ClassNotFoundException: Didn't find class "ai.bitlabs.sdk.BitLabs" on path: DexPathList[[zip file "/data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/lib/arm64, /data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
2024/02/06 00:08:58.595 4151 4212 Error Unity 	at dalvik.sys

**Comment by omaRaad** [comment]
@nguyenthanhloc191919 This is the same in the photo. I need more logs than that.

What you sent says that the BitLabs class wasn't found, but it doesn't say why. So how would I know what problem is?

**Comment by nguyenthanhloc191919** [comment]
Just that part in logcat is said about Bitlabs. Okay, i send you full log on logcat:

0001/01/01 00:00:00.000 -1 -1 Info  --------- beginning of main
2024/02/06 00:32:07.136 4618 4618 Info Zygote seccomp disabled by setenforce 0
2024/02/06 00:32:07.139 4618 4618 Info chatty uid=10078(com.LemonanaGames.MoneyBall) identical 12 lines
2024/02/06 00:32:08.527 4618 4662 Info chatty uid=10078(com.LemonanaGames.MoneyBall) UnityMain expire 21 lines
0001/01/01 00:00:00.000 -1 -1 Info  --------- beginning of system
2024/02/06 00:32:08.956 4618 4662 Error SchedPolicy set_timerslack_ns write failed: Operation not permitted
2024/02/06 00:32:09.148 4618 4694 Info chatty uid=10078(com.LemonanaGames.MoneyBall) UnityGfxDeviceW expire 3 lines
2024/02/06 00:32:09.317 4618 4696 Info chatty uid=10078(com.LemonanaGames.MoneyBall) FMODAudioDevice expire 2 lines
2024/02/06 00:32:09.496 4618 4662 Info chatty uid=10078(com.LemonanaGames.MoneyBall) UnityMain expire 186 lines
2024/02/06 00:32:09.975 4618 4699 Info chatty uid=10078(com.LemonanaGames.MoneyBall) Thread-5 expire 12 lines
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.access$500(com.unity3d.player.UnityPlayer) ((null):1)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer$e$1.handleMessage(android.os.Message) ((null):115)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at void android.os.Looper.loop() (Looper.java:193)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at void com.unity3d.player.UnityPlayer$e.run() ((null):21)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal Caused by: java.lang.ClassNotFoundException: Didn't find class "android.os.OutcomeReceiver" on path: DexPathList[[zip file "/data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/lib/arm64, /data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at boolean com.applovin.impl.sdk.aa.Fr() (SourceFile:1)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at java.util.Map com.applovin.impl.sdk.o.CV() (SourceFile:432)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.o.<init>(com.applovin.impl.sdk.n) (SourceFile:34)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.Bh() (SourceFile:130)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.a(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:28)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.sdk.AppLovinSdk.getInstance(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:15)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.mediation.unity.MaxUnityAdManager.initializeSdkWithCompletionHandler(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback, com.applovin.mediation.unity.MaxUnityAdManager$Listener) (MaxUnityAdManager.java:13)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at void com.applovin.mediation.unity.MaxUnityPlugin.initializeSdk(java.lang.String, java.lang.String, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback) (MaxUnityPlugin.java:36)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.access$500(com.unity3d.player.UnityPlayer) ((null):1)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer$e$1.handleMessage(android.os.Message) ((null):115)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at void android.os.Looper.loop() (Looper.java:193)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal   at void com.unity3d.player.UnityPlayer$e.run() ((null):21)
2024/02/06 00:32:11.770 4618 4662 Info Games.MoneyBal 
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal Rejecting re-init on previously-failed class java.lang.Class<com.applovin.impl.sdk.aa$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/os/OutcomeReceiver;
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at boolean com.applovin.impl.sdk.aa.Fr() (SourceFile:1)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at java.util.Map com.applovin.impl.sdk.o.CV() (SourceFile:432)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.o.<init>(com.applovin.impl.sdk.n) (SourceFile:34)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.Bh() (SourceFile:130)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.a(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:28)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.sdk.AppLovinSdk.getInstance(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:15)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.mediation.unity.MaxUnityAdManager.initializeSdkWithCompletionHandler(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback, com.applovin.mediation.unity.MaxUnityAdManager$Listener) (MaxUnityAdManager.java:13)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at void com.applovin.mediation.unity.MaxUnityPlugin.initializeSdk(java.lang.String, java.lang.String, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback) (MaxUnityPlugin.java:36)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.access$500(com.unity3d.player.UnityPlayer) ((null):1)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer$e$1.handleMessage(android.os.Message) ((null):115)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at void android.os.Looper.loop() (Looper.java:193)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at void com.unity3d.player.UnityPlayer$e.run() ((null):21)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal Caused by: java.lang.ClassNotFoundException: Didn't find class "android.os.OutcomeReceiver" on path: DexPathList[[zip file "/data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/lib/arm64, /data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at boolean com.applovin.impl.sdk.aa.Fr() (SourceFile:1)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at java.util.Map com.applovin.impl.sdk.o.CV() (SourceFile:432)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.o.<init>(com.applovin.impl.sdk.n) (SourceFile:34)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.Bh() (SourceFile:130)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.a(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:28)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.sdk.AppLovinSdk.getInstance(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:15)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.mediation.unity.MaxUnityAdManager.initializeSdkWithCompletionHandler(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback, com.applovin.mediation.unity.MaxUnityAdManager$Listener) (MaxUnityAdManager.java:13)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at void com.applovin.mediation.unity.MaxUnityPlugin.initializeSdk(java.lang.String, java.lang.String, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback) (MaxUnityPlugin.java:36)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.access$500(com.unity3d.player.UnityPlayer) ((null):1)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer$e$1.handleMessage(android.os.Message) ((null):115)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at void android.os.Looper.loop() (Looper.java:193)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal   at void com.unity3d.player.UnityPlayer$e.run() ((null):21)
2024/02/06 00:32:11.771 4618 4662 Info Games.MoneyBal 
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal Rejecting re-init on previously-failed class java.lang.Class<com.applovin.impl.sdk.aa$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/os/OutcomeReceiver;
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at boolean com.applovin.impl.sdk.aa.Fr() (SourceFile:1)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at java.util.Map com.applovin.impl.sdk.o.CV() (SourceFile:432)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.o.<init>(com.applovin.impl.sdk.n) (SourceFile:34)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.Bh() (SourceFile:130)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.a(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:28)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.sdk.AppLovinSdk.getInstance(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:15)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.mediation.unity.MaxUnityAdManager.initializeSdkWithCompletionHandler(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback, com.applovin.mediation.unity.MaxUnityAdManager$Listener) (MaxUnityAdManager.java:13)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void com.applovin.mediation.unity.MaxUnityPlugin.initializeSdk(java.lang.String, java.lang.String, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback) (MaxUnityPlugin.java:36)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.access$500(com.unity3d.player.UnityPlayer) ((null):1)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer$e$1.handleMessage(android.os.Message) ((null):115)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void android.os.Looper.loop() (Looper.java:193)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void com.unity3d.player.UnityPlayer$e.run() ((null):21)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal Caused by: java.lang.ClassNotFoundException: Didn't find class "android.os.OutcomeReceiver" on path: DexPathList[[zip file "/data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/lib/arm64, /data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at boolean com.applovin.impl.sdk.aa.Fr() (SourceFile:1)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at java.util.Map com.applovin.impl.sdk.o.CV() (SourceFile:432)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.o.<init>(com.applovin.impl.sdk.n) (SourceFile:34)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.Bh() (SourceFile:130)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.a(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:28)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.sdk.AppLovinSdk.getInstance(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:15)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.mediation.unity.MaxUnityAdManager.initializeSdkWithCompletionHandler(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback, com.applovin.mediation.unity.MaxUnityAdManager$Listener) (MaxUnityAdManager.java:13)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void com.applovin.mediation.unity.MaxUnityPlugin.initializeSdk(java.lang.String, java.lang.String, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback) (MaxUnityPlugin.java:36)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.access$500(com.unity3d.player.UnityPlayer) ((null):1)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer$e$1.handleMessage(android.os.Message) ((null):115)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void android.os.Looper.loop() (Looper.java:193)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void com.unity3d.player.UnityPlayer$e.run() ((null):21)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal 
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal Rejecting re-init on previously-failed class java.lang.Class<com.applovin.impl.sdk.aa$3>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/os/OutcomeReceiver;
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at boolean com.applovin.impl.sdk.aa.Fr() (SourceFile:1)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at java.util.Map com.applovin.impl.sdk.o.CV() (SourceFile:432)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.o.<init>(com.applovin.impl.sdk.n) (SourceFile:34)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.Bh() (SourceFile:130)
2024/02/06 00:32:11.772 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.a(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:28)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.sdk.AppLovinSdk.getInstance(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:15)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.mediation.unity.MaxUnityAdManager.initializeSdkWithCompletionHandler(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback, com.applovin.mediation.unity.MaxUnityAdManager$Listener) (MaxUnityAdManager.java:13)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.applovin.mediation.unity.MaxUnityPlugin.initializeSdk(java.lang.String, java.lang.String, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback) (MaxUnityPlugin.java:36)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.access$500(com.unity3d.player.UnityPlayer) ((null):1)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer$e$1.handleMessage(android.os.Message) ((null):115)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void android.os.Looper.loop() (Looper.java:193)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.unity3d.player.UnityPlayer$e.run() ((null):21)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal Caused by: java.lang.ClassNotFoundException: Didn't find class "android.os.OutcomeReceiver" on path: DexPathList[[zip file "/data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/lib/arm64, /data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at boolean com.applovin.impl.sdk.aa.Fr() (SourceFile:1)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at java.util.Map com.applovin.impl.sdk.o.CV() (SourceFile:432)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.o.<init>(com.applovin.impl.sdk.n) (SourceFile:34)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.Bh() (SourceFile:130)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.a(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:28)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.sdk.AppLovinSdk.getInstance(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:15)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.mediation.unity.MaxUnityAdManager.initializeSdkWithCompletionHandler(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback, com.applovin.mediation.unity.MaxUnityAdManager$Listener) (MaxUnityAdManager.java:13)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.applovin.mediation.unity.MaxUnityPlugin.initializeSdk(java.lang.String, java.lang.String, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback) (MaxUnityPlugin.java:36)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.access$500(com.unity3d.player.UnityPlayer) ((null):1)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer$e$1.handleMessage(android.os.Message) ((null):115)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void android.os.Looper.loop() (Looper.java:193)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.unity3d.player.UnityPlayer$e.run() ((null):21)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal 
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal Rejecting re-init on previously-failed class java.lang.Class<com.applovin.impl.sdk.aa$3>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/os/OutcomeReceiver;
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at boolean com.applovin.impl.sdk.aa.Fr() (SourceFile:1)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at java.util.Map com.applovin.impl.sdk.o.CV() (SourceFile:432)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.o.<init>(com.applovin.impl.sdk.n) (SourceFile:34)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.Bh() (SourceFile:130)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.a(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:28)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.sdk.AppLovinSdk.getInstance(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:15)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.mediation.unity.MaxUnityAdManager.initializeSdkWithCompletionHandler(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback, com.applovin.mediation.unity.MaxUnityAdManager$Listener) (MaxUnityAdManager.java:13)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.applovin.mediation.unity.MaxUnityPlugin.initializeSdk(java.lang.String, java.lang.String, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback) (MaxUnityPlugin.java:36)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.access$500(com.unity3d.player.UnityPlayer) ((null):1)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer$e$1.handleMessage(android.os.Message) ((null):115)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void android.os.Looper.loop() (Looper.java:193)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.unity3d.player.UnityPlayer$e.run() ((null):21)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal Caused by: java.lang.ClassNotFoundException: Didn't find class "android.os.OutcomeReceiver" on path: DexPathList[[zip file "/data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/lib/arm64, /data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at boolean com.applovin.impl.sdk.aa.Fr() (SourceFile:1)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at java.util.Map com.applovin.impl.sdk.o.CV() (SourceFile:432)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.o.<init>(com.applovin.impl.sdk.n) (SourceFile:34)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.Bh() (SourceFile:130)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.applovin.impl.sdk.n.a(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:28)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.sdk.AppLovinSdk.getInstance(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, android.content.Context) (SourceFile:15)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at com.applovin.sdk.AppLovinSdk com.applovin.mediation.unity.MaxUnityAdManager.initializeSdkWithCompletionHandler(java.lang.String, com.applovin.sdk.AppLovinSdkSettings, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback, com.applovin.mediation.unity.MaxUnityAdManager$Listener) (MaxUnityAdManager.java:13)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.applovin.mediation.unity.MaxUnityPlugin.initializeSdk(java.lang.String, java.lang.String, com.applovin.mediation.unity.MaxUnityAdManager$BackgroundCallback) (MaxUnityPlugin.java:36)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer.access$500(com.unity3d.player.UnityPlayer) ((null):1)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at boolean com.unity3d.player.UnityPlayer$e$1.handleMessage(android.os.Message) ((null):115)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void android.os.Looper.loop() (Looper.java:193)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal   at void com.unity3d.player.UnityPlayer$e.run() ((null):21)
2024/02/06 00:32:11.773 4618 4662 Info Games.MoneyBal 
2024/02/06 00:32:11.806 4618 4662 Debug AppLovinSdk [TcfManager] Attempting to update consent from Additional Consent string: null
2024/02/06 00:32:11.817 4618 4662 Debug AppLovinSdk [AppLovinSdk] Setting plugin version: Max-Unity-6.0.1
2024/02/06 00:32:11.820 4618 4662 Debug AppLovinSdk [MaxInterstitialAd] Created new MaxInterstitialAd (MaxInterstitialAd{adUnitId='f779d69435cbbd03', adListener=null, revenueListener=null, requestListenernull, adReviewListenernull, isReady=false})
2024/02/06 00:32:11.821 4618 4662 Warn AppLovinSdk [AppLovinSdk] Attempted to load ad before SDK initialization. Please wait until after the SDK has initialized, e.g. AppLovinSdk.initializeSdk(Context, SdkInitializationListener).
2024/02/06 00:32:11.924 4618 4662 Info Unity TimeManager script is Ready.
2024/02/06 00:32:11.924 4618 4662 Info Unity TimeManger:Start()
2024/02/06 00:32:11.924 4618 4662 Info Unity 
2024/02/06 00:32:11.968 4618 4662 Info Unity TimeManager script is Ready.
2024/02/06 00:32:11.968 4618 4662 Info Unity TimeManager:Start()
2024/02/06 00:32:11.968 4618 4662 Info Unity 
2024/02/06 00:32:11.971 4618 4662 Info Unity connecting to php
2024/02/06 00:32:11.971 4618 4662 Info Unity <getTime>d__6:MoveNext()
2024/02/06 00:32:11.971 4618 4662 Info Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
2024/02/06 00:32:11.971 4618 4662 Info Unity 
2024/02/06 00:32:12.050 4618 4676 Debug NetworkSecurityConfig Using Network Security Config from resource network_security_config debugBuild: false
2024/02/06 00:32:12.063 4618 4662 Error Unity AndroidJavaException: java.lang.ClassNotFoundException: ai.bitlabs.sdk.BitLabs
2024/02/06 00:32:12.063 4618 4662 Error Unity java.lang.ClassNotFoundException: ai.bitlabs.sdk.BitLabs
2024/02/06 00:32:12.063 4618 4662 Error Unity 	at java.lang.Class.classForName(Native Method)
2024/02/06 00:32:12.063 4618 4662 Error Unity 	at java.lang.Class.forName(Class.java:453)
2024/02/06 00:32:12.063 4618 4662 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2024/02/06 00:32:12.063 4618 4662 Error Unity 	at com.unity3d.player.UnityPlayer.access$500(Unknown Source:1)
2024/02/06 00:32:12.063 4618 4662 Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:115)
2024/02/06 00:32:12.063 4618 4662 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:102)
2024/02/06 00:32:12.063 4618 4662 Error Unity 	at android.os.Looper.loop(Looper.java:193)
2024/02/06 00:32:12.063 4618 4662 Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:21)
2024/02/06 00:32:12.063 4618 4662 Error Unity Caused by: java.lang.ClassNotFoundException: Didn't find class "ai.bitlabs.sdk.BitLabs" on path: DexPathList[[zip file "/data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/lib/arm64, /data/app/com.LemonanaGames.MoneyBall-9YFpDHRMRVWnWzI1ap4SfQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
2024/02/06 00:32:12.063 4618 4662 Error Unity 	at dalvik.sys
2024/02/06 00:32:12.065 4618 4618 Debug AppLovinSdk [MaxUnityAdManager] Creating BANNER with ad unit id "b6a2bc242770f21e" and position: "bottom_center"
2024/02/06 00:32:12.070 4618 4662 Debug AppLovinSdk [MaxRewardedAd] Created new MaxRewardedAd (MaxRewardedAd{adUnitId='e9ce8674630d31bc', adListener=null, revenueListener=null, requestListenernull, adReviewListenernull, isReady=false})
2024/02/06 00:32:12.072 4618 4662 Warn AppLovinSdk [AppLovinSdk] Attempted to load ad before SDK initialization. Please wait until after the SDK has initialized, e.g. AppLovinSdk.initializeSdk(Context, SdkInitializationListener).
2024/02/06 00:32:12.135 4618 4618 Warn AppLovinSdk [AppLovinSdk] Attempted to load ad before SDK initialization. Please wait until after the SDK has initialized, e.g. AppLovinSdk.initializeSdk(Context, SdkInitializationListener).
2024/02/06 00:32:12.135 4618 4618 Debug AppLovinSdk [MaxUnityAdManager] Showing BANNER with ad unit id "b6a2bc242770f21e"
2024/02/06 00:32:13.205 4618 4662 Info Unity got the php information
2024/02/06 00:32:13.205 4618 4662 Info Unity <getTime>d__6:MoveNext()
2024/02/06 00:32:13.205 4618 4662 Info Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
2024/02/06 00:32:13.205 4618 4662 Info Unity 
2024/02/06 00:32:13.368 4618 4709 Warn DynamiteModule Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
2024/02/06 00:32:13.377 4618 4709 Info DynamiteModule Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
2024/02/06 00:32:13.377 4618 4709 Warn ProviderInstaller Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
2024/02/06 00:32:13.384 4618 4709 Warn Games.MoneyBal Unknown chunk type '200'.
2024/02/06 00:32:13.413 4618 4709 Info Games.MoneyBal The ClassLoaderContext is a special shared library.
2024/02/06 00:32:13.423 4618 4709 Info chatty uid=10078(com.LemonanaGames.MoneyBall) AppLovinSdk:sha identical 1 line
2024/02/06 00:32:13.443 4618 4709 Info Games.MoneyBal The ClassLoaderContext is a special shared library.
2024/02/06 00:32:13.507 4618 4709 Verbose NativeCrypto Registering com/google/android/gms/org/conscrypt/NativeCrypto's 304 native methods...
2024/02/06 00:32:13.647 4618 4709 Info ProviderInstaller Installed default security provider GmsCore_OpenSSL
2024/02/06 00:32:13.674 4618 4662 Info Unity Congrtulations
2024/02/06 00:32:13.674 4618 4662 Info Unity PlayFabManager:OnLoginAndroidSuccess(LoginResult)
2024/02/06 00:32:13.674 4618 4662 Info Unity PlayFab.Internal.PlayFabUnityHttp:OnResponse(String, CallRequestContainer)
2024/02/06 00:32:13.674 4618 4662 Info Unity PlayFab.Internal.<Post>d__12:MoveNext()
2024/02/06 00:32:13.674 4618 4662 Info Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
2024/02/06 00:32:13.674 4618 4662 Info Unity 
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk [AppLovinSdk] 
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk ========================================
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk =====AppLovin SDK=====
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk ===SDK Versions===
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Version: 12.0.0
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Plugin Version: Max-Unity-6.0.1
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Ad Review Version: 5.1.2
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk OM SDK Version: 1.4.1-Applovin
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk ===Device Info===
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk OS: 9 (P - API 28)
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk GAID: <Enable verbose logging to see the GAID to use for test devices - https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK>
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Model: SM-G965N
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Locale: vi_VN
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Emulator: false
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Tablet: false
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk ===App Info===
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Application ID: com.LemonanaGames.MoneyBall
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Target SDK: 33
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk ExoPlayer Version: 2015001
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk ===SDK Settings===
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk SDK Key: uVao4b4X7rWfWqKKBWlzs3CdRJd5s4G5PPugSW9Hol4swaSrOI2XagzJ5AyqFzQPuTkhKC62hae2ow3X4pAdSV
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Mediation Provider: max
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk TG: 100
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk AEI: 120
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk MEI: 127
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Test Mode On: false
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Verbose Logging On: false
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk ===Privacy States===
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Please review AppLovin MAX documentation to be compliant with regional privacy policies.
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk 
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Age Restricted User - No value set
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Has User Consent - No value set
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk "Do Not Sell" - No value set
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk ===MAX Terms Flow===
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Enabled: false
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Privacy Policy URI: null
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk Terms of Service URI: null
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk ===CMP (CONSENT MANAGEMENT PLATFORM)===
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk 
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk CMP Name - No value set
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk CMP SDK ID - No value set
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk CMP SDK Version - No value set
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk IABTCF_gdprApplies - No value set
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk IABTCF_TCString - No value set
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk IABTCF_AddtlConsent - No value set
2024/02/06 00:32:14.146 4618 4708 Debug AppLovinSdk ========================================
2024/02/06 00:32:14.658 4618 4662 Info Unity 2024-02-05
2024/02/06 00:32:14.658 4618 4662 Info Unity MainTimeHandler:getCurrentDateNow(String)
2024/02/06 00:32:14.658 4618 4662 Info Unity MainTimeHandler:<Getdata>b__6_0(GetUserDataResult)
2024/02/06 00:32:14.658 4618 4662 Info Unity PlayFab.Internal.PlayFabUnityHttp:OnResponse(String, CallRequestContainer)
2024/02/06 00:32:14.658 4618 4662 Info Unity PlayFab.Internal.<Post>d__12:MoveNext()
2024/02/06 00:32:14.658 4618 4662 Info Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
2024/02/06 00:32:14.658 4618 4662 Info Unity 
2024/02/06 00:32:14.660 4618 4662 Info Unity 2024-02-05
2024/02/06 00:32:14.660 4618 4662 Info Unity MainTimeHandler:getCurrentDateNow(String)
2024/02/06 00:32:14.660 4618 4662 Info Unity MainTimeHandler:<Getdata>b__6_0(GetUserDataResult)
2024/02/06 00:32:14.660 4618 4662 Info Unity PlayFab.Internal.PlayFabUnityHttp:OnResponse(String, CallRequestContainer)
2024/02/06 00:32:14.660 4618 4662 Info Unity PlayFab.Internal.<Post>d__12:MoveNext()
2024/02/06 00:32:14.660 4618 4662 Info Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
2024/02/06 00:32:14.660 4618 4662 Info Unity 
2024/02/06 00:32:14.672 4618 4662 Info Unity 0
2024/02/06 00:32:14.672 4618 4662 Info Unity MangerDaysTasks:SetUp(MainTimeHandler)
2024/02/06 00:32:14.672 4618 4662 Info Unity UnityEngine.Events.UnityEvent:Invoke()
2024/02/06 00:32:14.672 4618 4662 Info Unity PlayFab.Internal.PlayFabUnityHttp:OnResponse(String, CallRequestContainer)
2024/02/06 00:32:14.672 4618 4662 Info Unity PlayFab.Internal.<Post>d__12:MoveNext()
2024/02/06 00:32:14.672 4618 4662 Info Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
2024/02/06 00:32:14.672 4618 4662 Info Unity 
2024/02/06 00:32:14.868 4618 4709 Warn AppLovinSdk [AppLovinSdk] Current SDK version (12.0.0) is outdated. Please integrate the latest version of the AppLovin SDK (12.1.0). Doing so will improve your CPMs and ensure you have access to the latest revenue earning features.
2024/02/06 00:32:14.971 4618 4662 Info Unity got the php information
2024/02/06 00:32:14.971 4618 4662 Info Unity <getTime>d__6:MoveNext()
2024/02/06 00:32:14.971 4618 4662 Info Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
2024/02/06 00:32:14.971 4618 4662 Info Unity 
2024/02/06 00:32:15.532 4618 4662 Info Unity Popup Closed-> ButtonPresed: NotNow -> Resume Game
2024/02/06 00:32:15.532 4618 4662 Info Unity TestScript:PopupClosedMethod(PopupOptions)
2024/02/06 00:32:15.532 4618 4662 Info Unity RateGame:RatePopupWasClosed(PopupOptions)
2024/02/06 00:32:15.532 4618 4662 Info Unity GleyRateGame.<CloseEvent>d__14:MoveNext()
2024/02/06 00:32:15.532 4618 4662 Info Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
2024/02/06 00:32:15.532 4618 4662 Info Unity 
2024/02/06 00:32:15.834 4618 4662 Info Unity got the php information
2024/02/06 00:32:15.834 4618 4662 Info Unity <getTime>d__6:MoveNext()
2024/02/06 00:32:15.834 4618 4662 Info Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
2024/02/06 00:32:15.834 4618 4662 Info Unity 
2024/02/06 00:32:16.063 4618 4662 Info Unity Error
2024/02/06 00:32:16.063 4618 4662 Info Unity <getTime>d__6:MoveNext()
2024/02/06 00:32:16.063 4618 4662 Info Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
2024/02/06 00:32:16.063 4618 4662 Info Unity 
2024/02/06 00:32:16.069 4618 4662 Info Unity The date is : <!doctype html>
2024/02/06 00:32:16.069 4618 4662 Info Unity <html lang="en-us">
2024/02/06 00:32:16.069 4618 4662 Info Unity <head>
2024/02/06 00:32:16.069 4618 4662 Info Unity 
2024/02/06 00:32:16.069 4618 4662 Info Unity 	<script>
2024/02/06 00:32:16.069 4618 4662 Info Unity         (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
2024/02/06 00:32:16.069 4618 4662 Info Unity                 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
2024/02/06 00:32:16.069 4618 4662 Info Unity             m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
2024/02/06 00:32:16.069 4618 4662 Info Unity         })(window,document,'script','https:
2024/02/06 00:32:16.069 4618 4662 Info Unity <getTime>d__6:MoveNext()
2024/02/06 00:32:16.069 4618 4662 Info Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
2024/02/06 00:32:16.069 4618 4662 Info Unity 
2024/02/06 00:32:16.070 4618 4662 Info Unity The time is : 
2024/02/06 00:32:16.070 4618 4662 Info Unity <getTime>d__6:MoveNext()
2024/02/06 00:32:16.070 4618 4662 Info Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
2024/02/06 00:32:16.070 4618 4662 Info Unity 
2024/02/06 00:32:16.132 4618 4662 Info Unity got the php information
2024/02/06 00:32:16.132 4618 4662 Info Unity <getTime>d__6:MoveNext()
2024/02/06 00:32:16.132 4618 4662 Info Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
2024/02/06 00:32:16.132 4618 4662 Info Unity 
2024/02/06 00:32:08.957 4618 4662 Info chatty uid=10078(com.LemonanaGames.MoneyBall) UnityMain identical 14 lines
2024/02/06 00:32:08.957 4618 4662 Error SchedPolicy set_timerslack_ns write failed: Operation not permitted

**Comment by omaRaad** [comment]
@nguyenthanhloc191919 Thanks for sending the logs.

The only way I think is possible to workaround this is if you try to export the project, and then open it in Android Studio and try running from there. Have you tried that?

**Comment by nguyenthanhloc191919** [comment]
Thank you so much, i tried to export project to android studio and it working well. I will close this issues.
